"""empty message

Revision ID: 171d17dedd37
Revises: 20e33a4d080a
Create Date: 2020-09-13 17:08:03.975246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '171d17dedd37'
down_revision = '20e33a4d080a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('Show', 'star_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('star_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
